# Documentation Metadata
springdoc.openapi.info.title=Sales Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice handles CRUD operations \
                                   for the Sale domain object.
